CREATE USER sauvest PASSWORD 'sauvest';
CREATE USER social PASSWORD 'social';
GRANT SOCIAL TO SAUVEST;
CREATE USER auth PASSWORD 'auth';
GRANT AUTH TO SAUVEST;
CREATE DATABASE SAUVESTDB OWNER sauvest;
GRANT ALL PRIVILEGES ON DATABASE SAUVESTDB TO sauvest;